#!/bin/sh

echo "Setting sources..."
echo "deb http://debian.slimdevices.com stable main" | sudo tee /etc/apt/sources.list.d/squeezebox.list > /dev/null

sudo apt-get update

echo "Installing..."
sudo apt-get install -y squeezeboxserver
